import { styled } from "styled-components";

// https://singlediv.com/#fancy
export const Pancakes = styled.div`
  accent-color: auto;
  align-content: normal;
  align-items: normal;
  align-self: auto;
  alignment-baseline: auto;
  animation-composition: replace;
  animation-delay: 0s;
  animation-direction: normal;
  animation-duration: 0s;
  animation-fill-mode: none;
  animation-iteration-count: 1;
  animation-name: none;
  animation-play-state: running;
  animation-range-end: normal;
  animation-range-start: normal;
  animation-timeline: auto;
  animation-timing-function: ease;
  app-region: none;
  appearance: none;
  backdrop-filter: none;
  backface-visibility: visible;
  background-attachment: scroll, scroll, scroll, scroll;
  background-blend-mode: normal, normal, normal, normal;
  background-clip: border-box, border-box, border-box, border-box;
  background-color: rgb(205, 133, 63);
  background-image: radial-gradient(
      rgba(255, 255, 255, 0.2) 60%,
      rgba(255, 255, 255, 0) 62%
    ),
    radial-gradient(rgba(255, 255, 255, 0.2) 60%, rgba(255, 255, 255, 0) 62%),
    radial-gradient(rgba(255, 255, 255, 0.2) 60%, rgba(255, 255, 255, 0) 62%),
    radial-gradient(rgba(255, 255, 255, 0.2) 60%, rgba(255, 255, 255, 0) 62%);
  background-origin: padding-box, padding-box, padding-box, padding-box;
  background-position:
    8px 30px,
    11px 40px,
    99px 65px,
    122px 65px;
  background-repeat: no-repeat, no-repeat, no-repeat, no-repeat;
  background-size:
    10px 5px,
    20px 10px,
    14px 7px,
    10px 5px;
  baseline-shift: 0px;
  baseline-source: auto;
  block-size: 80px;
  border-block-end-color: rgb(139, 69, 19);
  border-block-end-style: solid;
  border-block-end-width: 2px;
  border-block-start-color: rgb(139, 69, 19);
  border-block-start-style: solid;
  border-block-start-width: 2px;
  border-bottom-color: rgb(139, 69, 19);
  border-bottom-left-radius: 50%;
  border-bottom-right-radius: 50%;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-collapse: separate;
  border-end-end-radius: 50%;
  border-end-start-radius: 50%;
  border-image-outset: 0;
  border-image-repeat: stretch;
  border-image-slice: 100%;
  border-image-source: none;
  border-image-width: 1;
  border-inline-end-color: rgb(139, 69, 19);
  border-inline-end-style: solid;
  border-inline-end-width: 2px;
  border-inline-start-color: rgb(139, 69, 19);
  border-inline-start-style: solid;
  border-inline-start-width: 2px;
  border-left-color: rgb(139, 69, 19);
  border-left-style: solid;
  border-left-width: 2px;
  border-right-color: rgb(139, 69, 19);
  border-right-style: solid;
  border-right-width: 2px;
  border-start-end-radius: 50%;
  border-start-start-radius: 50%;
  border-top-color: rgb(139, 69, 19);
  border-top-left-radius: 50%;
  border-top-right-radius: 50%;
  border-top-style: solid;
  border-top-width: 2px;
  bottom: 170px;
  box-shadow:
    rgb(222, 184, 135) 0px 6px 0px 2px,
    rgb(139, 69, 19) 0px 6px 0px 4px,
    rgb(205, 133, 63) -3px 20px 0px 0px,
    rgb(139, 69, 19) -3px 20px 0px 2px,
    rgb(222, 184, 135) -3px 26px 0px 4px,
    rgb(139, 69, 19) -3px 26px 0px 6px,
    rgb(205, 133, 63) 5px 40px 0px 0px,
    rgb(139, 69, 19) 5px 40px 0px 2px,
    rgb(222, 184, 135) 5px 46px 0px 4px,
    rgb(139, 69, 19) 5px 46px 0px 6px,
    rgba(139, 69, 19, 0.4) 5px 57px 0px 5px;
  box-sizing: border-box;
  break-after: auto;
  break-before: auto;
  break-inside: auto;
  buffered-rendering: auto;
  caption-side: top;
  caret-color: rgb(0, 0, 0);
  clear: none;
  clip: auto;
  clip-path: none;
  clip-rule: nonzero;
  color: rgb(0, 0, 0);
  color-interpolation: srgb;
  color-interpolation-filters: linearrgb;
  color-rendering: auto;
  column-count: auto;
  column-gap: normal;
  column-rule-color: rgb(0, 0, 0);
  column-rule-style: none;
  column-rule-width: 0px;
  column-span: none;
  column-width: auto;
  contain-intrinsic-block-size: none;
  contain-intrinsic-height: none;
  contain-intrinsic-inline-size: none;
  contain-intrinsic-size: none;
  contain-intrinsic-width: none;
  container-name: none;
  container-type: normal;
  content: normal;
  cursor: auto;
  cx: 0px;
  cy: 0px;
  d: none;
  direction: ltr;
  display: block;
  dominant-baseline: auto;
  empty-cells: show;
  fill: rgb(0, 0, 0);
  fill-opacity: 1;
  fill-rule: nonzero;
  filter: none;
  flex-basis: auto;
  flex-direction: row;
  flex-grow: 0;
  flex-shrink: 1;
  flex-wrap: nowrap;
  float: none;
  flood-color: rgb(0, 0, 0);
  flood-opacity: 1;
  font-family: Times;
  font-kerning: auto;
  font-optical-sizing: auto;
  font-palette: normal;
  font-size: 10px;
  font-stretch: 100%;
  font-style: normal;
  font-synthesis-small-caps: auto;
  font-synthesis-style: auto;
  font-synthesis-weight: auto;
  font-variant: normal;
  font-variant-alternates: normal;
  font-variant-caps: normal;
  font-variant-east-asian: normal;
  font-variant-ligatures: normal;
  font-variant-numeric: normal;
  font-weight: 400;
  grid-auto-columns: auto;
  grid-auto-flow: row;
  grid-auto-rows: auto;
  grid-column-end: auto;
  grid-column-start: auto;
  grid-row-end: auto;
  grid-row-start: auto;
  grid-template-areas: none;
  grid-template-columns: none;
  grid-template-rows: none;
  height: 80px;
  hyphenate-character: auto;
  hyphenate-limit-chars: auto;
  hyphens: manual;
  image-orientation: from-image;
  image-rendering: auto;
  initial-letter: normal;
  inline-size: 200px;
  inset-block-end: 170px;
  inset-block-start: 200px;
  inset-inline-end: 328.25px;
  inset-inline-start: 428.25px;
  isolation: auto;
  justify-content: normal;
  justify-items: normal;
  justify-self: auto;
  left: 428.25px;
  letter-spacing: normal;
  lighting-color: rgb(255, 255, 255);
  line-break: auto;
  line-height: 10px;
  list-style-image: none;
  list-style-position: outside;
  list-style-type: disc;
  margin-block-end: 0px;
  margin-block-start: -50px;
  margin-bottom: 0px;
  margin-inline-end: 0px;
  margin-inline-start: -100px;
  margin-left: -100px;
  margin-right: 0px;
  margin-top: -50px;
  marker-end: none;
  marker-mid: none;
  marker-start: none;
  mask-type: luminance;
  math-depth: 0;
  math-shift: normal;
  math-style: normal;
  max-block-size: none;
  max-height: none;
  max-inline-size: none;
  max-width: none;
  min-block-size: 0px;
  min-height: 0px;
  min-inline-size: 0px;
  min-width: 0px;
  mix-blend-mode: normal;
  object-fit: fill;
  object-position: 50% 50%;
  object-view-box: none;
  offset-anchor: auto;
  offset-distance: 0px;
  offset-path: none;
  offset-position: auto;
  offset-rotate: auto 0deg;
  opacity: 1;
  order: 0;
  orphans: 2;
  outline-color: rgb(0, 0, 0);
  outline-offset: 0px;
  outline-style: none;
  outline-width: 0px;
  overflow-anchor: auto;
  overflow-clip-margin: 0px;
  overflow-wrap: normal;
  overflow-x: visible;
  overflow-y: visible;
  overscroll-behavior-block: auto;
  overscroll-behavior-inline: auto;
  padding-block-end: 0px;
  padding-block-start: 0px;
  padding-bottom: 0px;
  padding-inline-end: 0px;
  padding-inline-start: 0px;
  padding-left: 0px;
  padding-right: 0px;
  padding-top: 0px;
  paint-order: normal;
  perspective: none;
  perspective-origin: 100px 40px;
  pointer-events: auto;
  position: absolute;
  r: 0px;
  resize: none;
  right: 328.25px;
  rotate: none;
  row-gap: normal;
  ruby-position: over;
  rx: auto;
  ry: auto;
  scale: none;
  scroll-behavior: auto;
  scroll-margin-block-end: 0px;
  scroll-margin-block-start: 0px;
  scroll-margin-inline-end: 0px;
  scroll-margin-inline-start: 0px;
  scroll-padding-block-end: auto;
  scroll-padding-block-start: auto;
  scroll-padding-inline-end: auto;
  scroll-padding-inline-start: auto;
  scroll-timeline-axis: block;
  scroll-timeline-name: none;
  scrollbar-gutter: auto;
  shape-image-threshold: 0;
  shape-margin: 0px;
  shape-outside: none;
  shape-rendering: auto;
  speak: normal;
  stop-color: rgb(0, 0, 0);
  stop-opacity: 1;
  stroke: none;
  stroke-dasharray: none;
  stroke-dashoffset: 0px;
  stroke-linecap: butt;
  stroke-linejoin: miter;
  stroke-miterlimit: 4;
  stroke-opacity: 1;
  stroke-width: 1px;
  tab-size: 8;
  table-layout: auto;
  text-align: center;
  text-align-last: auto;
  text-anchor: start;
  text-decoration: none solid rgb(0, 0, 0);
  text-decoration-color: rgb(0, 0, 0);
  text-decoration-line: none;
  text-decoration-skip-ink: auto;
  text-decoration-style: solid;
  text-emphasis-color: rgb(0, 0, 0);
  text-emphasis-position: over;
  text-emphasis-style: none;
  text-indent: 0px;
  text-overflow: clip;
  text-rendering: auto;
  text-shadow: none;
  text-size-adjust: auto;
  text-transform: none;
  text-underline-position: auto;
  text-wrap: wrap;
  timeline-scope: none;
  top: 200px;
  touch-action: auto;
  transform: none;
  transform-origin: 100px 40px;
  transform-style: flat;
  transition-delay: 0s;
  transition-duration: 0s;
  transition-property: all;
  transition-timing-function: ease;
  translate: none;
  unicode-bidi: normal;
  user-select: auto;
  vector-effect: none;
  vertical-align: baseline;
  view-timeline-axis: block;
  view-timeline-inset: 0px;
  view-timeline-name: none;
  view-transition-name: none;
  visibility: visible;
  white-space-collapse: collapse;
  widows: 2;
  width: 200px;
  will-change: auto;
  word-break: normal;
  word-spacing: 0px;
  writing-mode: horizontal-tb;
  x: 0px;
  y: 0px;
  z-index: auto;
  zoom: 1;
  -webkit-border-horizontal-spacing: 0px;
  -webkit-border-image: none;
  -webkit-border-vertical-spacing: 0px;
  -webkit-box-align: stretch;
  -webkit-box-decoration-break: slice;
  -webkit-box-direction: normal;
  -webkit-box-flex: 0;
  -webkit-box-ordinal-group: 1;
  -webkit-box-orient: horizontal;
  -webkit-box-pack: start;
  -webkit-box-reflect: none;
  -webkit-font-smoothing: auto;
  -webkit-highlight: none;
  -webkit-line-break: auto;
  -webkit-line-clamp: none;
  -webkit-locale: "en";
  -webkit-mask-box-image: none;
  -webkit-mask-box-image-outset: 0;
  -webkit-mask-box-image-repeat: stretch;
  -webkit-mask-box-image-slice: 0 fill;
  -webkit-mask-box-image-source: none;
  -webkit-mask-box-image-width: auto;
  -webkit-mask-clip: border-box;
  -webkit-mask-composite: source-over;
  -webkit-mask-image: none;
  -webkit-mask-origin: border-box;
  -webkit-mask-position: 0% 0%;
  -webkit-mask-repeat: repeat;
  -webkit-mask-size: auto;
  -webkit-print-color-adjust: economy;
  -webkit-rtl-ordering: logical;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0.18);
  -webkit-text-combine: none;
  -webkit-text-decorations-in-effect: none;
  -webkit-text-fill-color: rgb(0, 0, 0);
  -webkit-text-orientation: vertical-right;
  -webkit-text-security: none;
  -webkit-text-stroke-color: rgb(0, 0, 0);
  -webkit-text-stroke-width: 0px;
  -webkit-user-drag: auto;
  -webkit-user-modify: read-only;
  -webkit-writing-mode: horizontal-tb;

  &::before {
    accent-color: auto;
    align-content: normal;
    align-items: normal;
    align-self: auto;
    alignment-baseline: auto;
    animation-composition: replace;
    animation-delay: 0s;
    animation-direction: normal;
    animation-duration: 0s;
    animation-fill-mode: none;
    animation-iteration-count: 1;
    animation-name: none;
    animation-play-state: running;
    animation-range-end: normal;
    animation-range-start: normal;
    animation-timeline: auto;
    animation-timing-function: ease;
    app-region: none;
    appearance: none;
    backdrop-filter: none;
    backface-visibility: visible;
    background-attachment: scroll;
    background-blend-mode: normal;
    background-clip: border-box;
    background-color: rgb(255, 255, 255);
    background-image: none;
    background-origin: padding-box;
    background-position: 0% 0%;
    background-repeat: repeat;
    background-size: auto;
    baseline-shift: 0px;
    baseline-source: auto;
    block-size: 60px;
    border-block-end-color: rgb(139, 69, 19);
    border-block-end-style: solid;
    border-block-end-width: 2px;
    border-block-start-color: rgb(139, 69, 19);
    border-block-start-style: solid;
    border-block-start-width: 2px;
    border-bottom-color: rgb(139, 69, 19);
    border-bottom-left-radius: 60px 25px;
    border-bottom-right-radius: 60px 25px;
    border-bottom-style: solid;
    border-bottom-width: 2px;
    border-collapse: separate;
    border-end-end-radius: 60px 25px;
    border-end-start-radius: 60px 25px;
    border-image-outset: 0;
    border-image-repeat: stretch;
    border-image-slice: 100%;
    border-image-source: none;
    border-image-width: 1;
    border-inline-end-color: rgb(139, 69, 19);
    border-inline-end-style: solid;
    border-inline-end-width: 2px;
    border-inline-start-color: rgb(139, 69, 19);
    border-inline-start-style: solid;
    border-inline-start-width: 2px;
    border-left-color: rgb(139, 69, 19);
    border-left-style: solid;
    border-left-width: 2px;
    border-right-color: rgb(139, 69, 19);
    border-right-style: solid;
    border-right-width: 2px;
    border-start-end-radius: 80px 40px;
    border-start-start-radius: 80px 40px;
    border-top-color: rgb(139, 69, 19);
    border-top-left-radius: 80px 40px;
    border-top-right-radius: 80px 40px;
    border-top-style: solid;
    border-top-width: 2px;
    bottom: 22px;
    box-shadow:
      rgba(139, 69, 19, 0.2) 0px -8px 0px 0px inset,
      rgba(139, 69, 19, 0.2) 0px 8px 0px 0px;
    box-sizing: border-box;
    break-after: auto;
    break-before: auto;
    break-inside: auto;
    buffered-rendering: auto;
    caption-side: top;
    caret-color: rgb(0, 0, 0);
    clear: none;
    clip: auto;
    clip-path: none;
    clip-rule: nonzero;
    color: rgb(0, 0, 0);
    color-interpolation: srgb;
    color-interpolation-filters: linearrgb;
    color-rendering: auto;
    column-count: auto;
    column-gap: normal;
    column-rule-color: rgb(0, 0, 0);
    column-rule-style: none;
    column-rule-width: 0px;
    column-span: none;
    column-width: auto;
    contain-intrinsic-block-size: none;
    contain-intrinsic-height: none;
    contain-intrinsic-inline-size: none;
    contain-intrinsic-size: none;
    contain-intrinsic-width: none;
    container-name: none;
    container-type: normal;
    content: "";
    cursor: auto;
    cx: 0px;
    cy: 0px;
    d: none;
    direction: ltr;
    display: block;
    dominant-baseline: auto;
    empty-cells: show;
    fill: rgb(0, 0, 0);
    fill-opacity: 1;
    fill-rule: nonzero;
    filter: none;
    flex-basis: auto;
    flex-direction: row;
    flex-grow: 0;
    flex-shrink: 1;
    flex-wrap: nowrap;
    float: none;
    flood-color: rgb(0, 0, 0);
    flood-opacity: 1;
    font-family: Times;
    font-kerning: auto;
    font-optical-sizing: auto;
    font-palette: normal;
    font-size: 10px;
    font-stretch: 100%;
    font-style: normal;
    font-synthesis-small-caps: auto;
    font-synthesis-style: auto;
    font-synthesis-weight: auto;
    font-variant: normal;
    font-variant-alternates: normal;
    font-variant-caps: normal;
    font-variant-east-asian: normal;
    font-variant-ligatures: normal;
    font-variant-numeric: normal;
    font-weight: 400;
    grid-auto-columns: auto;
    grid-auto-flow: row;
    grid-auto-rows: auto;
    grid-column-end: auto;
    grid-column-start: auto;
    grid-row-end: auto;
    grid-row-start: auto;
    grid-template-areas: none;
    grid-template-columns: none;
    grid-template-rows: none;
    height: 60px;
    hyphenate-character: auto;
    hyphenate-limit-chars: auto;
    hyphens: manual;
    image-orientation: from-image;
    image-rendering: auto;
    initial-letter: normal;
    inline-size: 150px;
    inset-block-end: 22px;
    inset-block-start: -6px;
    inset-inline-end: 16px;
    inset-inline-start: 30px;
    isolation: auto;
    justify-content: normal;
    justify-items: normal;
    justify-self: auto;
    left: 30px;
    letter-spacing: normal;
    lighting-color: rgb(255, 255, 255);
    line-break: auto;
    line-height: 10px;
    list-style-image: none;
    list-style-position: outside;
    list-style-type: disc;
    margin-block-end: 0px;
    margin-block-start: 0px;
    margin-bottom: 0px;
    margin-inline-end: 0px;
    margin-inline-start: 0px;
    margin-left: 0px;
    margin-right: 0px;
    margin-top: 0px;
    marker-end: none;
    marker-mid: none;
    marker-start: none;
    mask-type: luminance;
    math-depth: 0;
    math-shift: normal;
    math-style: normal;
    max-block-size: none;
    max-height: none;
    max-inline-size: none;
    max-width: none;
    min-block-size: 0px;
    min-height: 0px;
    min-inline-size: 0px;
    min-width: 0px;
    mix-blend-mode: normal;
    object-fit: fill;
    object-position: 50% 50%;
    object-view-box: none;
    offset-anchor: auto;
    offset-distance: 0px;
    offset-path: none;
    offset-position: auto;
    offset-rotate: auto 0deg;
    opacity: 1;
    order: 0;
    orphans: 2;
    outline-color: rgb(0, 0, 0);
    outline-offset: 0px;
    outline-style: none;
    outline-width: 0px;
    overflow-anchor: auto;
    overflow-clip-margin: 0px;
    overflow-wrap: normal;
    overflow-x: visible;
    overflow-y: visible;
    overscroll-behavior-block: auto;
    overscroll-behavior-inline: auto;
    padding-block-end: 0px;
    padding-block-start: 0px;
    padding-bottom: 0px;
    padding-inline-end: 0px;
    padding-inline-start: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-top: 0px;
    paint-order: normal;
    perspective: none;
    perspective-origin: 75px 30px;
    pointer-events: auto;
    position: absolute;
    r: 0px;
    resize: none;
    right: 16px;
    rotate: none;
    row-gap: normal;
    ruby-position: over;
    rx: auto;
    ry: auto;
    scale: none;
    scroll-behavior: auto;
    scroll-margin-block-end: 0px;
    scroll-margin-block-start: 0px;
    scroll-margin-inline-end: 0px;
    scroll-margin-inline-start: 0px;
    scroll-padding-block-end: auto;
    scroll-padding-block-start: auto;
    scroll-padding-inline-end: auto;
    scroll-padding-inline-start: auto;
    scroll-timeline-axis: block;
    scroll-timeline-name: none;
    scrollbar-gutter: auto;
    shape-image-threshold: 0;
    shape-margin: 0px;
    shape-outside: none;
    shape-rendering: auto;
    speak: normal;
    stop-color: rgb(0, 0, 0);
    stop-opacity: 1;
    stroke: none;
    stroke-dasharray: none;
    stroke-dashoffset: 0px;
    stroke-linecap: butt;
    stroke-linejoin: miter;
    stroke-miterlimit: 4;
    stroke-opacity: 1;
    stroke-width: 1px;
    tab-size: 8;
    table-layout: auto;
    text-align: center;
    text-align-last: auto;
    text-anchor: start;
    text-decoration: none solid rgb(0, 0, 0);
    text-decoration-color: rgb(0, 0, 0);
    text-decoration-line: none;
    text-decoration-skip-ink: auto;
    text-decoration-style: solid;
    text-emphasis-color: rgb(0, 0, 0);
    text-emphasis-position: over;
    text-emphasis-style: none;
    text-indent: 0px;
    text-overflow: clip;
    text-rendering: auto;
    text-shadow: none;
    text-size-adjust: auto;
    text-transform: none;
    text-underline-position: auto;
    text-wrap: wrap;
    timeline-scope: none;
    top: -6px;
    touch-action: auto;
    transform: none;
    transform-origin: 75px 30px;
    transform-style: flat;
    transition-delay: 0s;
    transition-duration: 0s;
    transition-property: all;
    transition-timing-function: ease;
    translate: none;
    unicode-bidi: normal;
    user-select: auto;
    vector-effect: none;
    vertical-align: baseline;
    view-timeline-axis: block;
    view-timeline-inset: 0px;
    view-timeline-name: none;
    view-transition-name: none;
    visibility: visible;
    white-space-collapse: collapse;
    widows: 2;
    width: 150px;
    will-change: auto;
    word-break: normal;
    word-spacing: 0px;
    writing-mode: horizontal-tb;
    x: 0px;
    y: 0px;
    z-index: auto;
    zoom: 1;
    -webkit-border-horizontal-spacing: 0px;
    -webkit-border-image: none;
    -webkit-border-vertical-spacing: 0px;
    -webkit-box-align: stretch;
    -webkit-box-decoration-break: slice;
    -webkit-box-direction: normal;
    -webkit-box-flex: 0;
    -webkit-box-ordinal-group: 1;
    -webkit-box-orient: horizontal;
    -webkit-box-pack: start;
    -webkit-box-reflect: none;
    -webkit-font-smoothing: auto;
    -webkit-highlight: none;
    -webkit-line-break: auto;
    -webkit-line-clamp: none;
    -webkit-locale: "en";
    -webkit-mask-box-image: none;
    -webkit-mask-box-image-outset: 0;
    -webkit-mask-box-image-repeat: stretch;
    -webkit-mask-box-image-slice: 0 fill;
    -webkit-mask-box-image-source: none;
    -webkit-mask-box-image-width: auto;
    -webkit-mask-clip: border-box;
    -webkit-mask-composite: source-over;
    -webkit-mask-image: none;
    -webkit-mask-origin: border-box;
    -webkit-mask-position: 0% 0%;
    -webkit-mask-repeat: repeat;
    -webkit-mask-size: auto;
    -webkit-print-color-adjust: economy;
    -webkit-rtl-ordering: logical;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0.18);
    -webkit-text-combine: none;
    -webkit-text-decorations-in-effect: none;
    -webkit-text-fill-color: rgb(0, 0, 0);
    -webkit-text-orientation: vertical-right;
    -webkit-text-security: none;
    -webkit-text-stroke-color: rgb(0, 0, 0);
    -webkit-text-stroke-width: 0px;
    -webkit-user-drag: auto;
    -webkit-user-modify: read-only;
    -webkit-writing-mode: horizontal-tb;
  }
  &::after {
    accent-color: auto;
    align-content: normal;
    align-items: normal;
    align-self: auto;
    alignment-baseline: auto;
    animation-composition: replace;
    animation-delay: 0s;
    animation-direction: normal;
    animation-duration: 0s;
    animation-fill-mode: none;
    animation-iteration-count: 1;
    animation-name: none;
    animation-play-state: running;
    animation-range-end: normal;
    animation-range-start: normal;
    animation-timeline: auto;
    animation-timing-function: ease;
    app-region: none;
    appearance: none;
    backdrop-filter: none;
    backface-visibility: visible;
    background-attachment: scroll;
    background-blend-mode: normal;
    background-clip: border-box;
    background-color: rgb(250, 240, 230);
    background-image: none;
    background-origin: padding-box;
    background-position: 0% 0%;
    background-repeat: repeat;
    background-size: auto;
    baseline-shift: 0px;
    baseline-source: auto;
    block-size: 3px;
    border-block-end-color: rgb(0, 0, 0);
    border-block-end-style: none;
    border-block-end-width: 0px;
    border-block-start-color: rgb(0, 0, 0);
    border-block-start-style: none;
    border-block-start-width: 0px;
    border-bottom-color: rgb(0, 0, 0);
    border-bottom-left-radius: 50%;
    border-bottom-right-radius: 50%;
    border-bottom-style: none;
    border-bottom-width: 0px;
    border-collapse: separate;
    border-end-end-radius: 50%;
    border-end-start-radius: 50%;
    border-image-outset: 0;
    border-image-repeat: stretch;
    border-image-slice: 100%;
    border-image-source: none;
    border-image-width: 1;
    border-inline-end-color: rgb(0, 0, 0);
    border-inline-end-style: none;
    border-inline-end-width: 0px;
    border-inline-start-color: rgb(0, 0, 0);
    border-inline-start-style: none;
    border-inline-start-width: 0px;
    border-left-color: rgb(0, 0, 0);
    border-left-style: none;
    border-left-width: 0px;
    border-right-color: rgb(0, 0, 0);
    border-right-style: none;
    border-right-width: 0px;
    border-start-end-radius: 50%;
    border-start-start-radius: 50%;
    border-top-color: rgb(0, 0, 0);
    border-top-left-radius: 50%;
    border-top-right-radius: 50%;
    border-top-style: none;
    border-top-width: 0px;
    bottom: 78px;
    box-shadow:
      rgb(34, 139, 34) 0px 10px 0px 1px,
      rgb(34, 139, 34) 20px 5px 0px 1px,
      rgb(34, 139, 34) 30px 10px 0px 1px,
      rgb(34, 139, 34) 50px 5px 0px 1px,
      rgb(34, 139, 34) -36px 22px 0px 1px,
      rgb(34, 139, 34) -20px 32px 0px 1px,
      rgb(34, 139, 34) -10px 30px 0px 1px,
      rgb(34, 139, 34) 50px 30px 0px 1px,
      rgb(34, 139, 34) 79px 24px 0px 1px,
      rgb(250, 240, 230) -26px 18px 0px 0px,
      rgb(17, 17, 17) -24px 20px 0px 6px,
      rgb(250, 240, 230) -4px 18px 0px 0px,
      rgb(17, 17, 17) -2px 20px 0px 6px,
      rgb(250, 240, 230) 11px 20px 0px 0px,
      rgb(17, 17, 17) 12px 22px 0px 6px,
      rgb(250, 240, 230) 31px 21px 0px 0px,
      rgb(17, 17, 17) 32px 23px 0px 6px,
      rgb(17, 17, 17) 42px 20px 0px 6px,
      rgb(250, 240, 230) 61px 23px 0px 0px,
      rgb(17, 17, 17) 62px 25px 0px 6px,
      rgb(17, 17, 17) 2px 2px 0px 6px,
      rgb(250, 240, 230) 16px -1px 0px 0px,
      rgb(17, 17, 17) 17px 1px 0px 6px,
      rgb(250, 240, 230) 30px 3px 0px 0px,
      rgb(17, 17, 17) 31px 5px 0px 6px,
      rgb(250, 240, 230) 49px 0px 0px 0px,
      rgb(17, 17, 17) 50px 2px 0px 6px,
      rgb(250, 240, 230) -10px 9px 0px 0px,
      rgb(17, 17, 17) -9px 11px 0px 6px,
      rgb(250, 240, 230) 11px 9px 0px 0px,
      rgb(17, 17, 17) 12px 11px 0px 6px,
      rgb(250, 240, 230) 40px 9px 0px 0px,
      rgb(17, 17, 17) 41px 11px 0px 6px,
      rgb(17, 17, 17) 3px 13px 0px 6px,
      rgb(17, 17, 17) 23px 13px 0px 6px,
      rgb(17, 17, 17) 31px 13px 0px 6px,
      rgb(17, 17, 17) 55px 11px 0px 6px,
      rgb(250, 240, 230) 70px 9px 0px 0px,
      rgb(17, 17, 17) 71px 11px 0px 6px,
      rgb(250, 240, 230) 21px 36px 0px 0px,
      rgb(17, 17, 17) 22px 38px 0px 6px;
    box-sizing: border-box;
    break-after: auto;
    break-before: auto;
    break-inside: auto;
    buffered-rendering: auto;
    caption-side: top;
    caret-color: rgb(0, 0, 0);
    clear: none;
    clip: auto;
    clip-path: none;
    clip-rule: nonzero;
    color: rgb(0, 0, 0);
    color-interpolation: srgb;
    color-interpolation-filters: linearrgb;
    color-rendering: auto;
    column-count: auto;
    column-gap: normal;
    column-rule-color: rgb(0, 0, 0);
    column-rule-style: none;
    column-rule-width: 0px;
    column-span: none;
    column-width: auto;
    contain-intrinsic-block-size: none;
    contain-intrinsic-height: none;
    contain-intrinsic-inline-size: none;
    contain-intrinsic-size: none;
    contain-intrinsic-width: none;
    container-name: none;
    container-type: normal;
    content: "";
    cursor: auto;
    cx: 0px;
    cy: 0px;
    d: none;
    direction: ltr;
    display: block;
    dominant-baseline: auto;
    empty-cells: show;
    fill: rgb(0, 0, 0);
    fill-opacity: 1;
    fill-rule: nonzero;
    filter: none;
    flex-basis: auto;
    flex-direction: row;
    flex-grow: 0;
    flex-shrink: 1;
    flex-wrap: nowrap;
    float: none;
    flood-color: rgb(0, 0, 0);
    flood-opacity: 1;
    font-family: Times;
    font-kerning: auto;
    font-optical-sizing: auto;
    font-palette: normal;
    font-size: 10px;
    font-stretch: 100%;
    font-style: normal;
    font-synthesis-small-caps: auto;
    font-synthesis-style: auto;
    font-synthesis-weight: auto;
    font-variant: normal;
    font-variant-alternates: normal;
    font-variant-caps: normal;
    font-variant-east-asian: normal;
    font-variant-ligatures: normal;
    font-variant-numeric: normal;
    font-weight: 400;
    grid-auto-columns: auto;
    grid-auto-flow: row;
    grid-auto-rows: auto;
    grid-column-end: auto;
    grid-column-start: auto;
    grid-row-end: auto;
    grid-row-start: auto;
    grid-template-areas: none;
    grid-template-columns: none;
    grid-template-rows: none;
    height: 3px;
    hyphenate-character: auto;
    hyphenate-limit-chars: auto;
    hyphens: manual;
    image-orientation: from-image;
    image-rendering: auto;
    initial-letter: normal;
    inline-size: 3px;
    inset-block-end: 78px;
    inset-block-start: -5px;
    inset-inline-end: 113px;
    inset-inline-start: 80px;
    isolation: auto;
    justify-content: normal;
    justify-items: normal;
    justify-self: auto;
    left: 80px;
    letter-spacing: normal;
    lighting-color: rgb(255, 255, 255);
    line-break: auto;
    line-height: 10px;
    list-style-image: none;
    list-style-position: outside;
    list-style-type: disc;
    margin-block-end: 0px;
    margin-block-start: 0px;
    margin-bottom: 0px;
    margin-inline-end: 0px;
    margin-inline-start: 0px;
    margin-left: 0px;
    margin-right: 0px;
    margin-top: 0px;
    marker-end: none;
    marker-mid: none;
    marker-start: none;
    mask-type: luminance;
    math-depth: 0;
    math-shift: normal;
    math-style: normal;
    max-block-size: none;
    max-height: none;
    max-inline-size: none;
    max-width: none;
    min-block-size: 0px;
    min-height: 0px;
    min-inline-size: 0px;
    min-width: 0px;
    mix-blend-mode: normal;
    object-fit: fill;
    object-position: 50% 50%;
    object-view-box: none;
    offset-anchor: auto;
    offset-distance: 0px;
    offset-path: none;
    offset-position: auto;
    offset-rotate: auto 0deg;
    opacity: 1;
    order: 0;
    orphans: 2;
    outline-color: rgb(0, 0, 0);
    outline-offset: 0px;
    outline-style: none;
    outline-width: 0px;
    overflow-anchor: auto;
    overflow-clip-margin: 0px;
    overflow-wrap: normal;
    overflow-x: visible;
    overflow-y: visible;
    overscroll-behavior-block: auto;
    overscroll-behavior-inline: auto;
    padding-block-end: 0px;
    padding-block-start: 0px;
    padding-bottom: 0px;
    padding-inline-end: 0px;
    padding-inline-start: 0px;
    padding-left: 0px;
    padding-right: 0px;
    padding-top: 0px;
    paint-order: normal;
    perspective: none;
    perspective-origin: 1.5px 1.5px;
    pointer-events: auto;
    position: absolute;
    r: 0px;
    resize: none;
    right: 113px;
    rotate: none;
    row-gap: normal;
    ruby-position: over;
    rx: auto;
    ry: auto;
    scale: none;
    scroll-behavior: auto;
    scroll-margin-block-end: 0px;
    scroll-margin-block-start: 0px;
    scroll-margin-inline-end: 0px;
    scroll-margin-inline-start: 0px;
    scroll-padding-block-end: auto;
    scroll-padding-block-start: auto;
    scroll-padding-inline-end: auto;
    scroll-padding-inline-start: auto;
    scroll-timeline-axis: block;
    scroll-timeline-name: none;
    scrollbar-gutter: auto;
    shape-image-threshold: 0;
    shape-margin: 0px;
    shape-outside: none;
    shape-rendering: auto;
    speak: normal;
    stop-color: rgb(0, 0, 0);
    stop-opacity: 1;
    stroke: none;
    stroke-dasharray: none;
    stroke-dashoffset: 0px;
    stroke-linecap: butt;
    stroke-linejoin: miter;
    stroke-miterlimit: 4;
    stroke-opacity: 1;
    stroke-width: 1px;
    tab-size: 8;
    table-layout: auto;
    text-align: center;
    text-align-last: auto;
    text-anchor: start;
    text-decoration: none solid rgb(0, 0, 0);
    text-decoration-color: rgb(0, 0, 0);
    text-decoration-line: none;
    text-decoration-skip-ink: auto;
    text-decoration-style: solid;
    text-emphasis-color: rgb(0, 0, 0);
    text-emphasis-position: over;
    text-emphasis-style: none;
    text-indent: 0px;
    text-overflow: clip;
    text-rendering: auto;
    text-shadow: none;
    text-size-adjust: auto;
    text-transform: none;
    text-underline-position: auto;
    text-wrap: wrap;
    timeline-scope: none;
    top: -5px;
    touch-action: auto;
    transform: none;
    transform-origin: 1.5px 1.5px;
    transform-style: flat;
    transition-delay: 0s;
    transition-duration: 0s;
    transition-property: all;
    transition-timing-function: ease;
    translate: none;
    unicode-bidi: normal;
    user-select: auto;
    vector-effect: none;
    vertical-align: baseline;
    view-timeline-axis: block;
    view-timeline-inset: 0px;
    view-timeline-name: none;
    view-transition-name: none;
    visibility: visible;
    white-space-collapse: collapse;
    widows: 2;
    width: 3px;
    will-change: auto;
    word-break: normal;
    word-spacing: 0px;
    writing-mode: horizontal-tb;
    x: 0px;
    y: 0px;
    z-index: auto;
    zoom: 1;
    -webkit-border-horizontal-spacing: 0px;
    -webkit-border-image: none;
    -webkit-border-vertical-spacing: 0px;
    -webkit-box-align: stretch;
    -webkit-box-decoration-break: slice;
    -webkit-box-direction: normal;
    -webkit-box-flex: 0;
    -webkit-box-ordinal-group: 1;
    -webkit-box-orient: horizontal;
    -webkit-box-pack: start;
    -webkit-box-reflect: none;
    -webkit-font-smoothing: auto;
    -webkit-highlight: none;
    -webkit-line-break: auto;
    -webkit-line-clamp: none;
    -webkit-locale: "en";
    -webkit-mask-box-image: none;
    -webkit-mask-box-image-outset: 0;
    -webkit-mask-box-image-repeat: stretch;
    -webkit-mask-box-image-slice: 0 fill;
    -webkit-mask-box-image-source: none;
    -webkit-mask-box-image-width: auto;
    -webkit-mask-clip: border-box;
    -webkit-mask-composite: source-over;
    -webkit-mask-image: none;
    -webkit-mask-origin: border-box;
    -webkit-mask-position: 0% 0%;
    -webkit-mask-repeat: repeat;
    -webkit-mask-size: auto;
    -webkit-print-color-adjust: economy;
    -webkit-rtl-ordering: logical;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0.18);
    -webkit-text-combine: none;
    -webkit-text-decorations-in-effect: none;
    -webkit-text-fill-color: rgb(0, 0, 0);
    -webkit-text-orientation: vertical-right;
    -webkit-text-security: none;
    -webkit-text-stroke-color: rgb(0, 0, 0);
    -webkit-text-stroke-width: 0px;
    -webkit-user-drag: auto;
    -webkit-user-modify: read-only;
    -webkit-writing-mode: horizontal-tb;
  }
`;
